import { FormEvent, useState } from 'react'
import { ArrowLeft, Save } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { Button, Card } from '@/components/ui'
import { saveDevotional } from '@/data/devotionals'

export function DevotionalCreator() {
  const navigate = useNavigate()
  const [form, setForm] = useState({ title: '', category: '', reference: '', translation: 'ESV', hook: '', insight: '' })
  const [error, setError] = useState('')
  const update = (field: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [field]: event.target.value })
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await saveDevotional(form); navigate('/devotionals') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save this devotional.') } }
  return <div className="mx-auto max-w-2xl space-y-5"><Link to="/devotionals" className="inline-flex items-center gap-2 text-sm font-bold text-ink/50"><ArrowLeft size={17} /> Devotionals</Link><div><p className="text-xs font-bold uppercase tracking-widest text-coral">Share a reflection</p><h1 className="mt-1 font-display text-4xl font-bold">Create a devotional</h1></div><Card className="p-6 sm:p-8"><form onSubmit={submit} className="space-y-5"><label className="block text-sm font-bold">Title<input required value={form.title} onChange={update('title')} placeholder="A title that draws people in" className="mt-2 w-full rounded-2xl border-2 border-ink/10 px-4 py-3 font-normal outline-none focus:border-coral" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Category<input required value={form.category} onChange={update('category')} placeholder="Hope, trust, purpose..." className="mt-2 w-full rounded-2xl border-2 border-ink/10 px-4 py-3 font-normal outline-none focus:border-coral" /></label><label className="block text-sm font-bold">Reference<input required value={form.reference} onChange={update('reference')} placeholder="John 3:16" className="mt-2 w-full rounded-2xl border-2 border-ink/10 px-4 py-3 font-normal outline-none focus:border-coral" /></label></div><label className="block text-sm font-bold">Translation<input required value={form.translation} onChange={update('translation')} className="mt-2 w-full rounded-2xl border-2 border-ink/10 px-4 py-3 font-normal outline-none focus:border-coral" /></label><label className="block text-sm font-bold">Opening thought<textarea required value={form.hook} onChange={update('hook')} rows={3} placeholder="What question or feeling does this meet?" className="mt-2 w-full resize-none rounded-2xl border-2 border-ink/10 px-4 py-3 font-normal outline-none focus:border-coral" /></label><label className="block text-sm font-bold">Core insight<textarea required value={form.insight} onChange={update('insight')} rows={5} placeholder="What would you like someone to carry with them?" className="mt-2 w-full resize-none rounded-2xl border-2 border-ink/10 px-4 py-3 font-normal outline-none focus:border-coral" /></label>{error && <p className="text-sm font-bold text-coral">{error}</p>}<Button type="submit" className="w-full"><Save size={17} className="mr-2" /> Publish devotional</Button></form></Card></div>
}