create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'New player',
  avatar_url text,
  total_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_name text not null,
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index game_scores_leaderboard_idx on public.game_scores (game_name, score desc, created_at asc);

alter table public.profiles enable row level security;
alter table public.game_scores enable row level security;

create policy "authenticated users can read profiles" on public.profiles for select to authenticated using (true);
create policy "users can update their profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "users can read scores" on public.game_scores for select to authenticated using (true);
create policy "users can insert their scores" on public.game_scores for insert to authenticated with check (auth.uid() = user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', 'New player'));
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
